name: SMCustomItems
version: 1.0-SNAPSHOT
main: smplugs.smcustomitems.SMCustomItems
api-version: 1.13
description: Simple plugin with a explosion tool;
commands:
  destroyer:
    description: Base destroyer command
